### ISSUE TITLE
Checklist for before going live on W.org

### ISSUE THREAD

**Issue by Nikschavan** [brainstormforce/bb-bootstrap-alerts#2]
- [x] Make plugin translation ready. See #1
- [x] Rename the [main fil](https://github.com/brainstormforce/bb-bootstrap-alerts/blob/master/bb-notifications.php)e to be same as the plugin slug (`bb-bootstrap-alerts.php`)
- [x] Add readme.txt, see #3

**Comment by akashdbsf** [comment]
The plugin is ready for translation.
Renamed main file to `bb-bootstrap-alerts.php`.
Added readme.txt file in the plugin
